server:
  port: 80
eureka:
  instance:
    # 注册的实例名
    instance-id: cloud-consumer-order80
  client:
    service-url:
      # Eureka server的地址
      #单机
      #defaultZone: http://localhost:7001/eureka/
      #集群
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
spring:
  application:
    #设置应用名
    name: cloud-order-consumer
