server:
  port: 8001
eureka:
  instance:
    # 注册的实例名
    instance-id: cloud-stream-provider8001
  client:
    service-url:
      # Eureka server的地址
      #单机
      #defaultZone: http://localhost:7001/eureka/
      #集群
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
spring:
  application:
    #设置应用名
    name: cloud-stream-provider
  rabbitmq:
    host: 192.168.126.11
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        # 广播消息 生产者绑定名称，myBroadcast是自定义的绑定名称，out代表生产者，0是固定写法
        myBroadcast-out-0:
          # 对应的真实的 RabbitMQ Exchange
          destination: my-broadcast-topic
        # 分组消费 生产者绑定名称，myGroup是自定义的绑定名称，out代表生产者，0是固定写法
        myGroup-out-0:
          # 对应的真实的 RabbitMQ Exchange
          destination: my-group-topic

