server:
  port: 8002
eureka:
  instance:
    # 注册名
    instance-id: cloud-provider-payment8002
  client:
    service-url:
      # Eureka server的地址
      #集群
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
      #单机
      #defaultZone: http://localhost:7001/eureka/
spring:
  application:
    #设置应用名
    name: cloud-payment-provider
  rabbitmq:
    host: 192.168.126.11
    port: 5672
    username: guest
    password: guest
## 设置zipkin和tracing配置 方便查看日志信息
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  zipkin:
    tracing:
      endpoint: http://192.168.126.11:9411/api/v2/spans
  tracing:
    sampling:
      # 采样率的概率，100%采样
      probability: 1.0
      # 每秒采样 数字最⾼为100
      #rate: 100